//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:2.0.50727.5477
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carubbi.CaptchaBreaker.Proxy.DTOs
{
    using System.Runtime.Serialization;
    
    /// <summary>
    /// 
    /// </summary>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CaptchaConfig", Namespace="http://schemas.datacontract.org/2004/07/Carubbi.CaptchaBreaker.DTOs")]
    public partial class CaptchaConfig : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool CaseSensitiveField;
        
        private bool ExecutarCalculoField;
        
        private int NumeroDePalavrasField;
        
        private int TamanhoMaximoField;
        
        private int TamanhoMinimoField;
        
        private Carubbi.CaptchaBreaker.Proxy.DTOs.TipoCaptcha TipoField;
        /// <summary>
        /// 
        /// </summary>
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CaseSensitive
        {
            get
            {
                return this.CaseSensitiveField;
            }
            set
            {
                this.CaseSensitiveField = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ExecutarCalculo
        {
            get
            {
                return this.ExecutarCalculoField;
            }
            set
            {
                this.ExecutarCalculoField = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroDePalavras
        {
            get
            {
                return this.NumeroDePalavrasField;
            }
            set
            {
                this.NumeroDePalavrasField = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TamanhoMaximo
        {
            get
            {
                return this.TamanhoMaximoField;
            }
            set
            {
                this.TamanhoMaximoField = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TamanhoMinimo
        {
            get
            {
                return this.TamanhoMinimoField;
            }
            set
            {
                this.TamanhoMinimoField = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Carubbi.CaptchaBreaker.Proxy.DTOs.TipoCaptcha Tipo
        {
            get
            {
                return this.TipoField;
            }
            set
            {
                this.TipoField = value;
            }
        }
    }
    /// <summary>
    /// 
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoCaptcha", Namespace="http://schemas.datacontract.org/2004/07/Carubbi.CaptchaBreaker.DTOs")]
    public enum TipoCaptcha : byte
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ApenasLetras = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ApenasNumeros = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Alfanumerico = 2,
    }
}


namespace Carubbi.CaptchaBreaker.Proxy
{
    /// <summary>
    /// 
    /// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ICaptchaBreaker")]
public interface ICaptchaBreaker
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaptchaBreaker/Break", ReplyAction="http://tempuri.org/ICaptchaBreaker/BreakResponse")]
    string Break(byte[] image, Carubbi.CaptchaBreaker.Proxy.DTOs.CaptchaConfig config);
}
    /// <summary>
    /// 
    /// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface ICaptchaBreakerChannel : ICaptchaBreaker, System.ServiceModel.IClientChannel
{
}
    /// <summary>
    /// 
    /// </summary>
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class GSACaptchaBreakerClient : System.ServiceModel.ClientBase<ICaptchaBreaker>, ICaptchaBreaker
{
    /// <summary>
    /// 
    /// </summary>
    public GSACaptchaBreakerClient()
    {
    }
    /// <summary>
    /// 
    /// </summary>
    /// <param name="endpointConfigurationName"></param>
    public GSACaptchaBreakerClient(string endpointConfigurationName) :
        base(endpointConfigurationName)
    {
    }
    /// <summary>
    /// 
    /// </summary>
    /// <param name="endpointConfigurationName"></param>
    /// <param name="remoteAddress"></param>
    public GSACaptchaBreakerClient(string endpointConfigurationName, string remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }
    /// <summary>
    /// 
    /// </summary>
    /// <param name="endpointConfigurationName"></param>
    /// <param name="remoteAddress"></param>
    public GSACaptchaBreakerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }
    /// <summary>
    /// 
    /// </summary>
    /// <param name="binding"></param>
    /// <param name="remoteAddress"></param>
    public GSACaptchaBreakerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
        base(binding, remoteAddress)
    {
    }
    /// <summary>
    /// 
    /// </summary>
    /// <param name="image"></param>
    /// <param name="config"></param>
    /// <returns></returns>
    public string Break(byte[] image, Carubbi.CaptchaBreaker.Proxy.DTOs.CaptchaConfig config)
    {
        return base.Channel.Break(image, config);
    }
}

}
